apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hifive.fullname" . }}-network-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hifive.name" . }}-email
      app.kubernetes.io/instance: {{ .Release.Name }}-email
      role: email
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ include "hifive.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          role: application
    ports:
    - protocol: TCP
      port: {{ .Values.email.smtp_port }}
