apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hifive.fullname" . }}-email
  labels:
{{ include "hifive.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hifive.name" . }}-email
      app.kubernetes.io/instance: {{ .Release.Name }}-email
      role: email
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hifive.name" . }}-email
        app.kubernetes.io/instance: {{ .Release.Name }}-email
        role: email
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "hifive.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: email-spool
          persistentVolumeClaim:
            claimName: {{ include "hifive.fullname" . }}-email-pvc
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.emailContainer.repository }}:{{ .Values.emailContainer.tag }}"
          imagePullPolicy: {{ .Values.emailContainer.pullPolicy }}
          volumeMounts:
            - name: email-spool
              mountPath: /var/spool/postfix
          env:
            - name: "ALLOWED_SENDER_DOMAINS"
              value: {{ .Values.emailContainer.sender_domain }}
            - name: "HOSTNAME"
              value: {{ .Values.emailContainer.hostname }}
          ports:
            - name: email
              containerPort: {{ .Values.email.smtp_port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.email.smtp_port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.email.smtp_port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
