---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hifive.fullname" . }}-email-pvc
spec:
  resources:
    requests:
      storage: {{ .Values.pvc.email.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.email.class }}

