apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hifive.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hifive.name" . }}
    helm.sh/chart: {{ include "hifive.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  db-username: {{ .Values.global.postgresql.postgresqlUsername | b64enc | quote }}
  db-password: {{ .Values.global.postgresql.postgresqlPassword | b64enc | quote }}
  email-bcc: {{ .Values.email.bcc | b64enc | quote }}
  email-sender: {{ .Values.email.sender | b64enc | quote }}
  google-client-id: {{ .Values.auth.google_client_id | b64enc | quote }}
  google-client-secret: {{ .Values.auth.google_client_secret | b64enc | quote }}
  ldap-password: {{ .Values.ldap.password | b64enc | quote }}
  ldap-username: {{ .Values.ldap.username | b64enc | quote }}

