{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hifive.serviceAccountName" . }}
  labels:
{{ include "hifive.labels" . | indent 4 }}
{{- end -}}
