require:
  - rubocop-performance
  - rubocop-rspec

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'Gemfile'
    - 'config.ru'
    - 'Rakefile'
    - 'Capfile'

Rails:
  Enabled: true

Style/Documentation:
  Exclude:
    - 'app/mailers/application_mailer.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 22

