version: '3.6'

services:
  web:
    build:
      context: ../../.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    entrypoint: sh -c 'bin/rails db:create db:migrate && bundle exec puma'
    volumes:
      - ../../.:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://postgres@database
    stdin_open: true
    tty: true

  database:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
