# Note: the application assumes one is always using PostgreSQL and supplying the environment variables defined below.
# The password field is optional, since it is not required for dev/test using the PG docker image

default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV.fetch("APPS_H5_DB_NAME") %>
  host: <%= ENV.fetch("APPS_H5_DB_HOST") %>
  username: <%= ENV.fetch("APPS_H5_DB_USER") %>
  <% if ENV["APPS_H5_DB_PW"].present? %>
  password: <%= ENV.fetch("APPS_H5_DB_PW") %>
  <% end %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
