# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
# On Linux: it is presumed you are smart enough to figure this out on your own.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch("DATABASE_URL") { "postgres://postgres@localhost" } %>

development:
  <<: *default
  database: hifive_development

test:
  <<: *default
  database: hifive_test

staging:
  <<: *default
  <% if ENV['RAILS_ENV'].eql? 'staging' %>
  database: <%= Rails.application.credentials.database[:staging][:database] %>
  host: <%= Rails.application.credentials.database[:staging][:host] %>
  username: <%= Rails.application.credentials.database[:staging][:username] %>
  password: <%= Rails.application.credentials.database[:staging][:password] %>
  <% end %>

production:
  <<: *default
  <% if ENV['RAILS_ENV'].eql? 'production' %>
  database: <%= Rails.application.credentials.database[:production][:database] %>
  host: <%= Rails.application.credentials.database[:production][:host] %>
  username: <%= Rails.application.credentials.database[:production][:username] %>
  password: <%= Rails.application.credentials.database[:production][:password] %>
  <% end %>
